######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 8 06:33:23 2011
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += connection.h ttcp.h
SOURCES += connection.cpp ttcp.cpp
