Document: tasker
Title: Debian tasker Manual
Author: <insert document author here>
Abstract: This manual describes what tasker is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tasker/tasker.sgml.gz

Format: postscript
Files: /usr/share/doc/tasker/tasker.ps.gz

Format: text
Files: /usr/share/doc/tasker/tasker.text.gz

Format: HTML
Index: /usr/share/doc/tasker/html/index.html
Files: /usr/share/doc/tasker/html/*.html


