.\" -*- nroff -*-
.TH winselect 1 "October 2006" "tasker version 0.01"
.SH NAME
winselect \- get information about a window
.SH SYNOPSIS
.B winselect
[
.B \--help
]
.SH DESCRIPTION
track the actions of an X user for the trasker system
.B winselect
a daemon that helps track the actions of a user.
.SH OPTIONS
.TP
.B \-s {server}
The host IP address running the trasker server.
.TP
.B \-V
Display the program version.
.TP
.B \-D
Debug -- do not run in background.
.SH AUTHOR
.B winselect
was written by G. Allen Morris III <gam3@gam3.com>. 
.SH BUGS
The server switch does not accept host names.  However the line below solves this problem.
 winselect --server `host google.com | grep address | head -1 | awk '{print $4 }'`
.SH AVAILABILITY
.B winselect
is part of the trasker task tracking system and is available from
http://trasker.sourceforge.net.
.SH SEE ALSO
.BR trasker (1)

